### ISSUE TITLE
库里包含了很多权限申请，会导致提审时有很多警告

### ISSUE THREAD

**Issue by ioser9527** [rztime/QuicklySwift#1]
![image](https://github.com/rztime/QuicklySwift/assets/10590616/498d6ecd-c167-4093-90f5-5ab1d258fef8)

**Comment by rztime** [comment]
我倒是没注意这个，我今天修复一下

**Comment by iimuy** [comment]
你好，推荐一个实现不错的权限申请库，可以参考下https://github.com/MxABC/LBXPermission.git

**Comment by ioser9527** [comment]
> 我倒是没注意这个，我今天修复一下

你好，推荐一个实现不错的权限申请库，可以参考下https://github.com/MxABC/LBXPermission.git

**Comment by ioser9527** [comment]
> > 我倒是没注意这个，我今天修复一下
> 
> 你好，推荐一个实现不错的权限申请库，可以参考下https://github.com/MxABC/LBXPermission.git

还有这个：https://github.com/delba/Permission

**Comment by rztime** [comment]
非常感谢，我写这个主要不是管理权限，只是方便判断，所以和你推荐的还不一样，我还要思考一下，

你那边可以先注释掉代码，先过审

**Comment by ioser9527** [comment]
> 非常感谢，我写这个主要不是管理权限，只是方便判断，所以和你推荐的还不一样，我还要思考一下，
> 
> 你那边可以先注释掉代码，先过审

好的

**Comment by noname004** [comment]
我也一样因为权限问题被拒

**Comment by rztime** [comment]
最新版本0.6.0已经解决这个问题了，之前造成的被拒，实在抱歉

**Comment by rztime** [comment]
> 我也一样因为权限问题被拒

抱歉抱歉，最新版本0.6.0已经解决这个问题了

**Comment by ioser9527** [comment]
> 最新版本0.6.0已经解决这个问题了，之前造成的被拒，实在抱歉

收到，谢谢啦
