### ISSUE TITLE
qhexString方法不能正确工作

### ISSUE THREAD

**Issue by iostang** [rztime/QuicklySwift#2]
<img width="964" alt="image" src="https://github.com/user-attachments/assets/371fc380-f2fa-443c-a37f-1deeb7b855b3">

在颜色转换方法中  如果 components 数组的长度小于预期（例如: 灰度颜色components的 count==2 里面只包含灰度值和透明度)
导致 qR, qG, qB, qA 的计算可能会不准确

**Comment by rztime** [comment]
感谢提醒, 稍后我会更新一下
